### ISSUE TITLE
What's the future of spark framework?

### ISSUE THREAD

**Issue by kamilgregorczyk** [perwendel/spark#1086]
Hi, what's the future of  this framework? Other frameworks are being extended quite heavily with things like http2, let's encrypt, reactive servlets etc. and I don't see spark being extended in any ways. Is it considered to be fully stable and there's no need for new features?

**Comment by tipsy** [comment]
@kamilgregorczyk It's hard to say. Spark hasn't needed to change much in the past few years. It's pretty stable now, so most commits are for bugfixes.

I spend most of my programming time working on [Javalin](https://javalin.io/), and I've talked to @perwendel about building Spark 3 on top of it. This would allow us to get a lot of these newer features to Spark users easily. I started a project for it: https://github.com/sparkjava/spark-javalin, but I haven't gotten very far.

Are you interesting in contributing?

**Comment by kamilgregorczyk** [comment]
Thanks for your answer, 
I didn't know about javalin, if there's javalin, why there's a need to create spark 3 ?

**Comment by pkkummermo** [comment]
I'm going to toss my 10c into this as well.

@tipsy has been a heavy maintainer of Spark the last few years, and a couple of years ago he started the idea of [Javalin](https://javalin.io/) ([github repo](https://github.com/tipsy/javalin)). I've been following Javalin since v0.0.1 and seen its development from a side project to the full fledged library/framework it is today. The reason behind Javalin as I've understood it was to create a more modern, simpler, and cleaner framework API, heavily influenced by Spark and koa.js, with new and modern features such as HTTP/2, async request handling and Websocket controls. The project is extremely well maintained (https://isitmaintained.com/project/tipsy/javalin) and David is always open for both PRs and suggestions on improvements.

For me Javalin _is_ Spark3, and as a former user of Spark I know that people will feel at home using it. Combined with tutorials of several common scenarios as well as an extremely good and thorough (yet simple) documentation it's super quick to get started.

I'm not bashing on Spark in any way, but I feel it has stopped its development and is now in it's "great and stable" phase, with no new features coming anytime soon.

Disclaimer: I've been invested in Javalin for a while after following it's progression so I'm a bit biased, but the project speaks for itself imho.

**Comment by toyg** [comment]
I'd be happy to volunteer to prune out github issues a bit, there are a ton of low-hanging fruits.

**Comment by robax** [comment]
I'd like to echo what @toyg said. I'd be happy to help maintain Spark as my org is a big user of it. However, since @perwendel is MIA there's no way to even get new PRs accepted. I'd hate to give @tipsy the burden of owning both Spark AND Javalin but I don't think there is anyone else.

I'd also like to echo what @pkkummermo said. Javalin is Spark3.

What do we do in @perwendel 's absence? If we can't get PRs in on Spark then working on the Spark Javalin wrapper and Javalin itself makes the most sense to me.

**Comment by tipsy** [comment]
@robax I don't have release rights, so while I can merge PRs it doesn't help too much. Per has also asked that I don't merge any breaking changes or new APIs, and I want to respect that. This means I'm pretty much limited to merging bugfixes and very small new features.

I'd be happy to give you push rights to https://github.com/sparkjava/spark-javalin if you want to contribute to the wrapper. I don't think it would take a lot of effort to finish it.

**Comment by perwendel** [comment]
The future of Spark is contemplated. There is going to be a 3.0 release where the API is revised and improved where possible and relevant extensions will be added.

**Comment by perwendel** [comment]
Closing due to off-topic discussions about other frameworks.

**Comment by kamilgregorczyk** [comment]
And that's all?

**Comment by robax** [comment]
Deleting legitimate, well-intentioned comments reflects really poorly on you and this project. I didn't get to see @tipsy and @toyg's responses to my comment that I made about a week ago. I don't know if it's possible but if you can, I humbly request you un-delete these comments @perwendel.

**Comment by toyg** [comment]
Uh, that’s... not nice. My comment just said I could volunteer to clean up github issues. Not mentioned anything else. :/

**Comment by tipsy** [comment]
While I don't agree with his decision, @perwendel doens't want other frameworks mentioned here at all. I will continue the discussion with him in private. 

@robax there's no way to un-delete a comment, and I can't repeat it. I'll lock this issue now.

**Comment by perwendel** [comment]
@robax @toyg It's a conflict of interest. I don't think it's appropriate to promote and discuss other, currently, competing frameworks here. That is better done on that particular project's page. I don't see that as very strange.

**Comment by perwendel** [comment]
@robax however, I do agree that deleting comments doesn't look good. It could be handled in a better way and I did it somewhat in irritation. There is a history to this.
