### ISSUE TITLE
Is there a way to change the RouteMatcher?

### ISSUE THREAD

**Issue by juanformoso** [perwendel/spark#126]
I want to change the SimpleRouteMatcher for it to expose all the routes for a mini documentation, but I can't seem to find how to use another one.

    private static synchronized void init() {
        if (!initialized) {
            routeMatcher = RouteMatcherFactory.get();
    (...)

And RouteMatcherFactory doesn't let me inject or change the object created.

**Comment by travisspencer** [comment]
This is actually impossible with the code as it is. If you use the Servlet `Filter`, you have to run `init` otherwise, `filterPath` will be null when `doFilter` is called. Thus, you have to completely replace the Servlet `Filter` in order to change the matcher. You also have to inherit from `SparkBase` and change `routeMatcher`. This is a major design flaw IMO as the matcher does not account for complicated scenarios where multiple identical MIME type are routed with varying lengths. In that case, the longest should be chosen and not always the last one added as the `SimpleMatcher` does.

**Comment by perwendel** [comment]
Currently no plan for changing the Route matcher via the API
