### ISSUE TITLE
Enhancement: concept of "finally" filter

### ISSUE THREAD

**Issue by revetkn** [perwendel/spark#195]
I noticed that "after" filter methods are not invoked if an exception occurs, making it possible to have mismatched "before"/"after" pairs.  Suppose I begin a database transaction in "before" and an exception occurs - the "after" does not fire, so it is up so some unrelated place like ExceptionMapper to perform cleanup.

I confirmed this by examining https://github.com/perwendel/spark/blob/master/src/main/java/spark/webserver/MatcherFilter.java

What do you think of introducing a "finally" filter, which would always execute, even in the face of an exception?  If you think it makes sense, I can probably come up with a pull request.  Or maybe there is a better way to do this out-of-the-box that I am missing and we don't need any Spark changes at all :)

**Comment by chillenious** [comment]
Just ran into this while going after a bug. I actually expected the 'after' filters to be executed regardless. Anyway, whether explicit or implicit, I think it is important that you can define filters that are always ran, exception or not.

**Comment by gutobortolozzo** [comment]
Hi @chillenious and @perwendel, a few months ago I submited the PR #217, can you take look and provide some feedback about the feature? 
When I needed this feature the code submited worked for me. Maybe it help you, and can be merged.

**Comment by chillenious** [comment]
Looked at it, but I'm not a developer on this project. Imho exceptions - in
particular because they are being used internally (halt) - should not block
exceptions. I'm using filters to clean up any thread locals, set headers I
always want to set regardless of the return, etc, and I had to implement a
pretty gnarly workaround to get that done.

Also, I don't think the before/ after filters are quite as convenient as
they first come across when compared to filters, as I often have the case
where I want to do something before and after, which now takes me two
filters and probably some temporary shared state to accomplish. Maybe
something to reconsider for a 2.0 version? :-)

**Comment by MouettE-SC** [comment]
PR has been merged, this issues can be closed now.
