### ISSUE TITLE
No enum constant spark.route.HttpMethod.propfind

### ISSUE THREAD

**Issue by pokev25** [perwendel/spark#242]
Has a connection to the Apache web server and proxy methods.

But propfind exception occurs.

---

[ERROR] MatcherFilter:211 - 
java.lang.IllegalArgumentException: No enum constant spark.route.HttpMethod.propfind        at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_25]        at spark.route.HttpMethod.valueOf(HttpMethod.java:22) ~[spark-core-2.1.jar:na]        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:125) ~[spark-core-2.1.jar:na]        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:126) [spark-core-2.1.jar:na]        at         at

**Comment by tipsy** [comment]
Could you provide some more context?

**Comment by pokev25** [comment]
Apache Webserver proxy - tomcat  - my spark.war  ::    Other web server type

my solution is just add 'propfind'
and does not occur execption

public enum HttpMethod {
    get, post, put, patch, delete, head, trace, connect, options, before, after, propfind
}

**Comment by guillaumeprevot** [comment]
I second this feature request but with a different proposition. The request is justified by HTTP extensions that may use other HTTP methods.

For instance, I would like to create a WEBDAV/CALDAV/CARDDAV server using Spark but these HTTP extensions use PROPFIND/PROPPATCH/MKCOL/MKCALENDAR/MOVE/REPORT methods. 

Instead of adding an infinite list of methods to HttpMethod enum, is it possible to get rid of enum and let us extend HTTP method at runtime ? 

As this is my first post, I would like to thank you for this great project !
Regards,
Guillaume


Question : is it possible to add PROPFIND HTTP method or, even better, avoid enum and allow us to use custom HTTP methods ?

**Comment by tipsy** [comment]
Please create a PR if you still need this.
