### ISSUE TITLE
Swagger support?

### ISSUE THREAD

**Issue by ckloppers** [perwendel/spark#258]
Anybody looking into baking-in swagger support?

**Comment by chillenious** [comment]
Would be nice to have. How would you imagine this would work roughly?

**Comment by tchoulihan** [comment]
I tried to do something like this before, but unfortunately annotations
don't seem to work correctly with lambda functions, so it'd be impossible.

For my project, I basically just created a mustache template html page for
the API documentation, and represented all the routes, examples, and
descriptions in a static .JSON file.

**Comment by chillenious** [comment]
Yeah, annotations won't work, which imho is fine because even if they would, it would be pretty horrible and pretty much negate everything that's nice about using Spark. The end of the day, swagger is a spec, so as long as you generate what it expects, it doesn't matter how you get there.

I think that at the minimum what Spark can do to facilitate swagger integration is make the model that it builds up internally more accessible. That'd be great to have regardless actually. Basically, we - framework clients - would have a way to introspect routes for the basics, like path and parameter info, and Spark could consider baking in more things - optionally - like content types etc and make that available for introspection when set. This would be a good start.

Beyond that (and building on top of that probably) Spark could consider building a tighter integration. Wouldn't be everyone's cup of tea to make Spark more opinionated (and have a larger conceptual surface area) I guess, though swagger being pretty much the defacto standard, this probably isn't so bad. Not sure what that would actually look like, but I would probably be thinking about adding a bunch of optional builders to build up meta data about the API. 

I really like (from a quick view) how https://github.com/metosin/compojure-api provides swagger support on top of compojure. Not so useful for this case, but maybe a source of inspiration somehow :-)

**Comment by smorin** [comment]
Spark is so easy to use, would be great if we could generate Swagger templates from Sparkframework.  Then documentation would be very easily supported.   Develop your code and just generate your documentation in a standard way.

**Comment by wenerme** [comment]
Any progress ?

**Comment by jeffpeiyt** [comment]
+1

**Comment by s4mpl3d** [comment]
chchchch

2016-04-21 9:02 GMT+02:00 Yuanteng (Jeff) Pei <notifications@github.com>:

**Comment by srlk** [comment]
It's possible to create swagger json if you can survive writing your routes without lambda expressions. You can check my sample project https://github.com/srlk/spark-swagger

**Comment by tipsy** [comment]
@srlk nice! Can we repost your tutorial on https://sparktutorials.github.io/ ?

**Comment by srlk** [comment]
Sure @tipsy

**Comment by pgKuantic** [comment]
Looks like the project has moved. All links are broken. 
Here is the new link: 
[https://github.com/cesinrm/spark-swagger](https://github.com/cesinrm/spark-swagger)

**Comment by TangMonk** [comment]
@pgKuantic , the tutorial link on readme is lost

**Comment by powerLambda** [comment]
"And each route has to be separate classes to make annotations happily parsesable.. Sorry (req, res) -> magic!"
https://serol.ro/posts/2016/swagger_sparkjava/

Really dislike the idea to abandon lambda expression  (req, res) -> magic!

**Comment by manusant** [comment]
Hi,
I´ve been working on a non-official Spark extension to suppor Swagger.
Check it out https://github.com/manusant/SparkSwagger
