### ISSUE TITLE
Google App Engine support

### ISSUE THREAD

**Issue by theiostream** [perwendel/spark#262]
Would it be possible to support Google App Engine somehow (or at least provide some documentation regarding the issue?)

Thank you.

**Comment by atonparker** [comment]
I was hopeful about this as well. I tried it out, and immediately ran into an issue with java.util.stream.Stream being a restricted class on App Engine. I believe this is because App Engine does not support Java 8, and restricted any classes introduced in that version. It's probably asking too much of Spark to support Java 7, since its entire design is based on Java 8 lambdas. So we should probably be bugging Google instead.

The App Engine issue is here: https://code.google.com/p/googleappengine/issues/detail?id=9537

**Comment by tipsy** [comment]
Seems ok to close this.
