### ISSUE TITLE
Can we have a non-static API?

### ISSUE THREAD

**Issue by gubby** [perwendel/spark#297]
(Perhaps there is already a way to do this, that I have missed... but looking at spark.SparkBase it looks unlikely)

The fact that all the methods (e.g. port(), get(), etc) are static, means that code using Spark is impossible to test, and Spark is no use in integration tests. Additionally, it prevents two servers being started in the same JVM (e.g. HTTPS/HTTP), which makes it unsuitable for quite a large number of use cases (e.g. HTTP-to-HTTPS redirection, for which I still need to run e.g. Apache).

Would it be possible to expose a more traditional API that is based on instance methods? I don't think the fluidity would be lost substantially:

```
Spark spark = new Spark();
spark.port(8080);
spark.get("/", this::homePage);
etc.
```

Thanks!

**Comment by phase** [comment]
You could copy all the methods and remove the `static`.

**Comment by gubby** [comment]
@phase Everything in spark.SparkBase would also need changing, and in a forked repo.

**Comment by magicgoose** [comment]
+1, this stuff needs refactoring, static API is inherently less flexible

**Comment by amarseillan** [comment]
im trying to implement this, but it gets hard when embedded in another application server, will keep you up to date!

**Comment by ribomation** [comment]
*Suggestion*: let the methods return `this`, aka cascade calls. 
For example:
```java
    new Spark()
      .port(8888)
      .get("/",...)
      .get("/ping",...)
      .start();
```

**Comment by magicgoose** [comment]
> Suggestion: let the methods return this, aka cascade calls. 

there's little benefit anywhere except "hello world" server examples…

**Comment by amarseillan** [comment]
>Suggestion: let the methods return this, aka cascade calls.
>there's little benefit anywhere except "hello world" server examples…

Yeah... unless you want it to be immutable for thread safety?

**Comment by magicgoose** [comment]
I don't see how it's related to immutability.
Anyway, I'm not saying that I'm against it, it'll probably be good to have

**Comment by amarseillan** [comment]
> I don't see how it's related to immutability.
You copy-on-write and return the new instance, just that

**Comment by amarseillan** [comment]
So I think I'll just upload a version without the feature of deploying spark in different application servers because I don't use that and I can't find a generic way to achieve it without static properties, I'll post the repo here when I have that so someone can check it out and maybe fix that

**Comment by magicgoose** [comment]
So it'll be possible to run 2 or more servers in one Java application? Then it's cool!

**Comment by amarseillan** [comment]
Yup =D!

**Comment by borud** [comment]
Moving away from static instances is, in my mind, the most important change that can be made to Sparkjava.  Not least to make it possible to write proper unit tests.  This is the one reason why we are only using Sparkjava experimentally and still on the lookout for a REST framework for Java.  If we fix that, then I have what I need.

Being able to chain calls would be very nice.  If people want static calls to save on typing, then you want chaining as per @ribomation's example.  The way I think would be useful to think about the API is to see it as a builder API.

    Spark spark = new SparkBuilder()
      .put(......) {....}
      .get(......) {....}
      .post(......) {....}
      .port(8080)
      .build();

Inconsistencies would then result in errors or exceptions during manipulation of the `SparkBuilder` or when you call `build()` on it.  *And the Spark instance is completely immutable*.   (Have a look at the objects generated by protobuffers in Java as an example)

And then the lifecycle is separate.  So just creating spark does not start it.  You have explicit control.

    spark.start((foo, bar) -> ...);
    spark.start(executor, (foo, bar) -> ...);

    spark.shutdown((foo, bar) -> ....);
    spark.shutdown().get();

etc

(Have no idea what parameter should be given to the listener. probably instance and perhaps throwable on errors?  Also, you might want to have a shutdownNow() which doesn't wait for connections to terminate etc)


But first things first:  static instance is the biggest obstacle to adoption for us right now.  Because it makes testing very, very awkward.

**Comment by borud** [comment]
As for having multiple, separate REST services in the same JVM, 3 out of 4 of the last projects I've worked on have that.  (And if you count unit tests:  since those execute in parallel and require strict separation to have predictable state and state transitions, we're talking tens of simultaneous, separate instances concurrently in the same JVM).  So at least for the projects I've worked on in the past decade, this isn't just theoretical.  It is a very real requirement.

**Comment by amarseillan** [comment]
:+1: perfect explanation of the motivation, next week I'll show you my
patch so we can think of a solution for other application servers

**Comment by borud** [comment]
@amarseillan Looking forward to it!

**Comment by amarseillan** [comment]
Well, as promised... I broke the Servlet functionality, any help will be appreciated =D, check it out [here](https://github.com/despegar/spark/tree/non_static)

**Comment by narve** [comment]
Is anybody still working on this? Or, more relevant, do we know if the non-static modifications will be accepted into the main project? 

I also consider using Spark for "serious" projects, but missing testability and lack of hooks are showstoppers for now.

**Comment by aaboyd** [comment]
Would love to see this change made.  @amarseillan are you still looking for help on fixing the servlet functionality?

Would this actually get pulled in?

**Comment by jean-morissette** [comment]
We also this change for projects going to production. What is the current situation?

**Comment by amarseillan** [comment]
I'm not using spark anymore =(

**Comment by borud** [comment]
Neither am I :(

**Comment by tipsy** [comment]
#499 <- Instance API will be part of 2.4

Example:
```
Service http = ignite()
          .port(1234)
          .staticFileLocation("/public")
          .threadPool(40);
http.get("/hello", (q, a) -> "Hello World!");
```

**Comment by borud** [comment]
Thanks!  This is great.  Just as I am starting a new Java project! :)

When is 2.4 going to hit the repositories?

**Comment by sp-1234** [comment]
@borud looks like 2.5 did already hit
