### ISSUE TITLE
Can we render from AWT image in spark?

### ISSUE THREAD

**Issue by ozooxo** [perwendel/spark#298]
I cannot put the images in `/public` folder and use as static resources, because the images are produced dynamically (I am actually using `ImageJ` to produce my image in backend with complicated algorithms, for which the image can finally be turned to AWT).

By surveying the spark source code, since [`java.spark.Response`](https://github.com/perwendel/spark/blob/master/src/main/java/spark/Response.java) has some private attribute `response` which is `javax.servlet.http.HttpServletResponse` finally is `javax.servlet.ServletResponse`, I think the approach should be something like

``` java
import java.awt.Image;

...

    public static void main(String[] args) throws IOException {

        final Image image = new ImageIcon("my-path-to-image.jpg").getImage();
        ???

        get("/test.jpeg", (request, response) -> {
                response.type("image/jpeg");

                return ???;
            }
        );
    }

...
```

In `javax.servlet.http.HttpServletResponse response`, we can kind of play with

``` java
        OutputStream out = response.getOutputStream();
        BufferedImage outImage = new BufferedImage(640, 360, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = outImage.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        JPEGImageEncoder encoder =  JPEGCodec.createJPEGEncoder(out);
        encoder.encode(outImage);
        out.close();
```

However, since `javax.servlet.http.HttpServletResponse response` is private in `java.spark.Response`, and there are only limited methods to use `java.spark.Response`, are their anyway for us to transform AWT images into the right format for returning in `get(...,  (request, response) -> {return ???})`? Thanks.

**Comment by chillenious** [comment]
I needed the ability to stream something not too long ago, and ran into
some issues with Spark. It's a bit of a hack, but this is how I did it
(will just paste in the fragment):

try (InputStream inputStream = zipFile.getInputStream(entry)) {
                // NOTE [Eelco] order seems to matter here... don't change
without testing!
                int bytesCopied = Streams.copy(inputStream,
response.raw().getOutputStream());
                String contentType = tika.detect(inputStream,
entry.getName());
                response.type(contentType);

                // This really sucks, but we have to flush the buffer, and
as we do, stuff we do afterwards to the
                // response won't have effect, hence we'll need to do it
here. Also note that if we'd return a byte
                // array, Spark would simply convert this to a string
(doesn't work so well)
                CacheBustingFilter.setHeaders(request, response);
                CrossOriginFilter.setHeaders(request, response);

                response.raw().setContentLength(bytesCopied);

                response.raw().flushBuffer(); // Do this or Spark will try
to set the body based on the return val
                // END of order matters
            }


which is called by this piece:

        bindGetForOrgAndUserRoutesWithAuthPart("content/:media-id/epub/*",
JsonView
                .withHandler((request, ctx, response) -> {
                    UUID mediaId = request.paramAsUUID("media-id");
                    String location = request.splat()[0];
                    ePubLoader.streamEpubZipEntry(mediaId, location,
request.getWrapped(), response);
                    return ""; // request is flushed, so this will be
ignored by Spark
                })

.withAuthorization(readAccessOrMediaIdWithinOrganizationScope())
                .build(ctxp));

That's a bunch of custom frameworking you see there, but the main piece is
that the return value will be ignored once you flush the buffer of the
underlying request.

I wouldn't be surprised if this breaks next upgrade (so we likely won't,
also because we have a bunch of other fixes in place to deal with
weaknesses of Spark, like the fact that filters aren't called after
exceptions, even if these exceptions are 'internal' like halt()). I think
there are enough of such issues (also e.g. getting rid of static methods)
that Spark could use a major internal overhaul (2.0?)... but maybe that's
just me being dense :-)

Eelco
