### ISSUE TITLE
Tests fail if port 4567 is in use

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#400]
Not sure if this is a bug, but we should probably use a random open port for tests. Or at least not 4567.

**Comment by jakaarl** [comment]
From my quick test, seemed like at least these tests are affected:
 * `BodyAvailabilityTest`
 * `BooksIntegrationTest`
 * `CookiesIntegrationTest`
 * `GenericIntegrationTest`
 * `GenericSecureIntegrationTest`
 * `GZipTest`
 * `StaticFilesTest`

These are affected, because they use the default port. Others are affected when their corresponding ports are taken: for example, `ServletTest`binds to port 9393. Also, `SparkTestUtil` is relevant here, since it needs to be passed the Spark port - typical test pattern is to pass the default port in setup phase and not specify a port to Spark, causing it to default to 4567. I guess this pattern should be replaced by binding to an automatically assigned port (by passing in 0 as port argument) and then digging out the assigned port and pass it to `SparkTestUtil`. Problem is, that the port cannot (as far as I could tell with a quick glance at the sources) be easily pried out from `JettySparkServer`.
