### ISSUE TITLE
please consider renaming the project

### ISSUE THREAD

**Issue by vnwarrior** [perwendel/spark#463]
https://www.google.co.in/search?q=spark+java+postgresql&oq=spark+java+postgresql&aqs=chrome..69i57.5059j0j1&sourceid=chrome&es_sm=93&ie=UTF-8

it is very, very, very hard to google for anything around this project because of the big name conflict with Apache Spark. and it becomes very hard to become productive. 

Taking an inspiration from TypeScript, you could also call it TypeSpark (P.S. TypeSpark.org is available) ... but please consider having something we can actually look for.

**Comment by tipsy** [comment]
We're looking into it.

**Comment by sandys** [comment]
@tipsy thanks!

**Comment by kodonnell** [comment]
Agree with @vnwarrior on this one - any progress? I thought I'd point out that I'm running a (web) Spark app from (big data) Spark ... well trying to. Not only does this make things even more confusing (especially when I'm searching for documentation on both!), but also when you get dependencies with the same name (i.e. "spark-core" for both). It doesn't break things, but it did have me confused for a while.

**Comment by tipsy** [comment]
Little progress I'm afraid. It's a very hard problem that we don't really have the capacity/skills to do deal with properly. We're open to suggestions though.

**Comment by kodonnell** [comment]
I've never done it before (so I'm probably missing something), but why not decide a new name and migrate on the next big release? I wouldn't worry about backward compatibility (though there may be a clever way to do that), and just rely on existing users (who want to upgrade) to make the code changes (as they usually have to do with big releases anyway). Overall, it's not going to take them long (a few `sed` commands should do most of it).

Then I guess it's just admin stuff - create a new (renamed) fork on github (leaving the old one round for maintenance), update the website, etc.

**Comment by tipsy** [comment]
It's not that hard to "just do it", but to come up with a new name that makes sense and doesn't collide with anything else, and doesn't cause us to confuse/lose our entire userbase, is a challenge. Then there's changing all the branding, redirecting old links, explaining to people who click old links that the project has been renamed, etc.

**Comment by sandys** [comment]
+1 on this suggestion. Spark is a very confusing name and IMHO Apache Spark
has the SEO + mindshare here.

I dont see a reason for fear. Firebird -> Firefox ,  Seomoz -> Moz,
Typesafe -> Lightbend (the Scala company. Read here
<https://www.lightbend.com/blog/typesafe-changes-name-to-lightbend> and here
<http://www.lightbend.com/blog/whats-in-a-name>) are good examples.

Old links will not vanish - you will just have a 301 redirect. Plus, i
would say that you would rank better and be more discoverable.

Also, i would simply post about this on Producthunt and Hacker News and
call it a day.

**Comment by kodonnell** [comment]
@tipsy, I agree that it's not easy, however it's largely just documentation-level changes. Some feedback on your arguments:

- names are hard ... but technically easy. Put another way, someone could come up with the perfect name in 5 seconds, and it'd be done.
- I'd suggest that part of your userbase is already "lost" in some sense: how many more users would you have if Google hadn't shown them Apache Spark? (And this will get worse and worse.) Or they got frustrated with the above points? Those who you do have are probably aware of the problem, and would welcome a change. And, if they're anything like me, then your userbase is probably already "confuse[d]", and it'd be less confusing to clear it up.

I see @sandys just made similar points.

**Comment by sandys** [comment]
i actually like the name TypeSpark - you anways have "NodeJS Developer? Using/Curious About TypeScript? Try Spark Instead!" on the front page.  Also the name is a derivative of the previous name .. so you are not very far away.

TypeSpark.org is still available.

**Comment by tipsy** [comment]
> I dont see a reason for fear. Firebird -> Firefox ,  Seomoz -> Moz,
>Typesafe -> Lightbend (the Scala company. Read here
The comments there are absolutely brutal though.

>how many more users would you have if Google hadn't shown them Apache Spark?
Not that many I would guess. If you already know what we're called you won't confuse us for Apache Spark, and for our most relevant web searches (like "java web framework"), Apache Spark is (obviously) not listed.

I have disliked the Spark name since I joined, so I understand where you're all coming from, but the vast majority of our users have never visited us on GitHub, and I'm not sure they know about Apache Spark. If we get one complaint about the name per hundred thousand views, I'm not sure it's worth changing. 
I still really want to though, and instead of releasing Spark 3.0 I would much prefer creating a new project XYZ 1.0. It bothers me a lot.

**Comment by kodonnell** [comment]
> for our most relevant web searches (like "java web framework"), Apache Spark is (obviously) not listed.

It may be me, but when I was searching, I went for 'spark java' (after finding it on one of the blogs about the "best web frameworks for java" etc.), in the same way I generally search '<language> <package>' e.g. 'python flask'. In addition, when I saw your website URI (sparkjava.com) I kept using that. As you'll see, Apache Spark is definitely there (and it's likely to be there more in future, in part due to the likes of Zeppelin which are kind of web frameworks for Apache Spark).

Is there any way you can gauge the feeling of the wider Spark community?

**Comment by sandys** [comment]
why don't you just send a survey? post it on your github page front, hacker
news, etc.

lets see what people want.

IMHO, you cannot beat google. and the first 10 results for anything related
to spark is Apache Spark. and people google a lot to understand code

**Comment by jakaarl** [comment]
I always defeat the "other Spark issue" by googling "sparkjava", but I guess that leaves out quite a bit of potentially useful search hits. So yes, perhaps a name change is in order. Some ideas:

 * "javatra", because "sinatra" and "scalatra" (but this would draw too much comparison?)
 * "frank", perhaps coupled with something descriptive ("java", "web", "server"?) for disambiguation?
 * "exude" - no software related hits comes up, refers to "express" as in ExpressJS

I kind of like "frank" or "exude", since the Spark API allows one to be "quite frank" and "express" one self rather clearly.

**Comment by ruurd** [comment]
I'm sort of used to searching for perwendel spark... BTW, which project came first? perwendel/spark or apache/spark?

**Comment by tipsy** [comment]
If I remember correctly, Apache Spark has earlier commits than Spark, but Spark was launched before Apache Spark.

**Comment by weickmanna** [comment]
The name conflict *is* definitely a shortcoming of this web framework. The impact of Apache Spark is just too big.
I wouldn't change to another web framework just because of this, sure. But if I were already thinking of changing for other reasons, it might "just push it over the top".

**Comment by p-h** [comment]
Try searching for anything related to this framework and caching. It's absolutely impossible. You can't even search with "-apache" because perwendel/spark is licensed under the Apache license. It doesn't matter who started first or who released first. All that matters is who show's up higher in search engines.
