### ISSUE TITLE
Routes, TemplateEngine and ModelAndView [discussion]

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#513]
The current syntax for using template engines is:

``` java
get(path, (request, response) -> {
    return new ModelAndView(model, templatePath);
}, new VelocityTemplateEngine());
```

If you have a class with all your route declarations, it will look something like this:

``` java
get(path1, Class::methodReturningModelAndView1, templateEngine);
get(path2, Class::methodReturningModelAndView2, templateEngine);
get(path3, Class::methodReturningModelAndView3, templateEngine);
```

I don't like this, so what I usually do is: 

``` java
get(path, (request, response) -> {
    return render(model, templatePath); //static method
});
```

Which gives you:

``` java
get(path1, Class::methodReturningString1);
get(path2, Class::methodReturningString2);
get(path3, Class::methodReturningString3);
```

I like this a lot more. In my mind a GET shouldn't be concerned with models, views, or template engines. It should map a path to some method that produces output.

I think we should deprecate the `get(path, modelAndView, templateEngine)` method.

Pros: 
- No overloading (one way of doing things)
- Cleaner code, clearer mapping between path/ouput
- Fewer concepts for new users to familiarize themselves with

Cons:
- ?

Thoughts? Am I missing something here?

**Comment by bademux** [comment]
Please take a look into #483 - we already have bicycle to ride:

Function<Result, String> render = result -> doExtraRenderingThere(result);
handler.andThen(render);

this way we can exdend `java.util.function.BiFunction<Request, Response, Object>` to do pre\post processing in flexible way with KISS interface from spark.

Spark side API:

```java
class Route{
 static class Builder{
   static Buider build(HttpMethod method, String path, BiFunction<Request,Response, String> handler){...}
   static Buider buildGet(String path, BiFunction<Request,Response, String> handler){...}

   Builder accept(MimeType type){...}

  Route toBuilder(){}
 }
}

class Spark{
 static class Builder{
  Builder addRoute(Route route);
...
  void build(){
  //process all routes here
  }
 }
}
```

**Comment by carsongross** [comment]
Hi There,

I agree that the current template syntax is a bit awkward.  Typically people are going to select one template engine and go with it, so including it in every route is redundant.  Also, currently you have to pick between returning a string or using a template, and there are cases where that isn't ideal.  Finally, I think we could improve the api so that people don't need to know about models and views, and can just invoke the template directly.

I've created a proposal for a new template syntax here:

https://github.com/carsongross/spark/commit/5788003209e65d9627617b35ecce914f5c4c00d5

- You set a global template renderer
- You invoke templates as closely to functions as possible
- I use varargs and an arg() helper method to get around the fact that java doesn't have a decent map literal syntax

**Comment by fwgreen** [comment]
**A bit of bikeshedding**:  If this does happen in the next major release, please consider swapping the positions of `model` and `templatePath` in the render method.  Java 9 brings with it [convenience factory methods for collections](http://openjdk.java.net/jeps/269) and a change in position would aid readability as the number of elements in the model increase.
```Java
get("/", (request, response) -> {
    return render("first.hbs", Map.of("title","First Page")); 
});

get("/next", (request, response) -> {
    List<String> fruit = List.of("apples", "oranges", "pears");
    return render("next.hbs", Map.of("title","Next Page", "greeting","Hello", "fruit",fruit)); 
});
```

**Comment by tipsy** [comment]
Added to v3 wishlist
