### ISSUE TITLE
Virtual Hosts

### ISSUE THREAD

**Issue by mcjp78** [perwendel/spark#575]
Hi,
How would I configure virtual hosts in spark? Like listen to domain 1 but not domain.2?

**Comment by dherges** [comment]
Uh, I'd probably try to solve that by infrastrucutre. Running multiple spark instances with a load balancer / proxy in front of that.


If you want to do that "in code": the ``spark.Service`` is initialized as a static ``SingletonHolder``. So you can't use the static ``get()``, ``post()``, ``put()``, et al. methods directly. You will need to create one ``Service`` instance per vhost and call methods on that instance. It's noted in the doc comments... https://github.com/perwendel/spark/blob/master/src/main/java/spark/Service.java#L39-L45

Try to set the ipAddress / host of the embedded jetty server. Could work like this, haven't tested though:

```java
Service foo = ignite();
foo.ipAddress("foo.domain1.local");
foo.get("/hello", (q, a) -> "Hello Foo!");

Service bar = ignite();
bar.ipAddress("bar.domain2.local");
bar.get("/hello", (q, a) -> "Hello Bar!");
```

If you're doing all this in a servlet container, you probably need to do even more things. Like implement a subclass of ``SparkFilter``, matching the Host header in ``doFilter()``. Then, have one filter instance registered per vhost, each with one ``SparkApplication`` again using a ``Service`` instance instead of the static methods.

**Comment by AzureusNation** [comment]
@mcjp78 I agree with @dherges with a proxy like apache or nginx in front and have multiple instance of Spark on different port numbers.

But another way in code is:
'''java
public class App {

    Spark sparkApp1 = new Spark() {{
        ipAddress("app1.test.local");
        port(4567);
        get("/", (request, response) -> "Test1");
    }};

    Spark sparkApp2 = new Spark() {{
        ipAddress("app2.test2.local");
        port(4568);
        get("/", (request, response) -> "Test2");
    }};
}
'''
