### ISSUE TITLE
after method is not invoked for static files

### ISSUE THREAD

**Issue by aurabhi** [perwendel/spark#591]
I am using the a global after method to log requests/response(access logs). The after method is not invoked for static files. I was expecting that the before and after methods are invoked irrespective of nature of content.

**Comment by MouettE-SC** [comment]
Before and after filters are never called for static resources because they are handled separately and that's expected (see #571 ). Access logs should be handled by webservers (jetty or external) and not by applications (that's what I think). Unfortunately there is no easy way to turn on access logs on the embedded jetty server (I've done in [here](url) if you're interested)

**Comment by pablogrisafi1975** [comment]
A quick hack to make them sort of work:

put your static files in a folder named 'filtered', inside resources, but DO not set that folder a staticFiles.location

then map like this:

```
		get("/filtered/:file", (req, res) -> {
			String resourceName = "/filtered/" + req.params("file");
			return filteredResource(req, res, resourceName);
		});
		get("/filtered/:folder1/:file", (req, res) -> {
			String resourceName = "/filtered/" + req.params("folder1") + "/" + req.params("file");
			return filteredResource(req, res, resourceName);
		});
		get("/filtered/:folder1/:folder2/:file", (req, res) -> {
			String resourceName = "/filtered/" + req.params("folder1") + "/" + req.params("folder2") + "/"
					+ req.params("file");
			return filteredResource(req, res, resourceName);
		});
		after("/filtered/*", (request, response) 
				-> response.header("spark1", "added by after-filter /filtered/*"));
		after((request, response) 
				-> response.header("spark2", "added by after-filter "));
	}

	public static Object filteredResource(Request req, Response res, String resourceName) throws IOException {
		try (InputStream inputStream = Main.class.getResourceAsStream(resourceName)) {
			if (inputStream == null) {
				halt(404, "File '" + req.pathInfo() + "' not found");
				return res.body();
			}
			IOUtils.copy(inputStream, res.raw().getOutputStream());
			return "";
		}
	}

```
I needed serveral mappings because could not din a way to map everything in one line. Implementation is sort of naive, some caching may improve performance

**Comment by AzureusNation** [comment]
I agree with @MouettE-SC this shouldn't be an issue with Spark, logs should be done via the web server and not the application.

**Comment by a3mon** [comment]
Well, logs aren't the only application for filters on static content.

**Comment by WayneDoherty** [comment]
I would like to call the after filter on static files in order to alter Cache-Control settings. 
As my Service Worker js files are served out of a static directory I would like to set those files to no-cache so that updates are always timely. Other files in the static directory I would serve with aggressive expiration times.

**Comment by tipsy** [comment]
Duplicates #571
