### ISSUE TITLE
Response with Umlaute wrong encoding 

### ISSUE THREAD

**Issue by lpmmo4231** [perwendel/spark#606]
I'm having issues with Umlaute in the response body. I have the following endpoint 
```java
get("/test", (request, response) -> {
    response.status(200);
    return "ÄÖÜäöüß";
});
```

When I access the resource with `curl` this results in
```
> GET /test HTTP/1.1
> Host: localhost:9002
> User-Agent: curl/7.45.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 05 Jul 2016 18:01:41 GMT
< Content-Type: text/html;charset=utf-8
< Transfer-Encoding: chunked
< Server: Jetty(9.3.6.v20151106)
<
├ä├û├£├ñ├Â├╝├ƒ* Connection #0 to host localhost left intact
```
The same problems occurs with XML and JSON responses. 
I am using OpenJDK 1.8.0.91-3.

**Comment by victorwss** [comment]
Is the java source code encoded with UFT-8?

**Comment by DittmarSteiner** [comment]
Had the same problem with Jetty or Netty based Servers.

I added the following line to my `~/.bashrc`:
`export JAVA_TOOL_OPTIONS='-Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF-8'`

In my `Dockerfile`s this looks like
`ENV JAVA_TOOL_OPTIONS '-Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF-8'`

Since then there were no more encoding problems.
_Hope this helps!_

**Comment by lpmmo4231** [comment]
After a little bit of trying I found out that this is an issue with `curl` under windows. I tested this under Win10 and got the error which led to this question. After that I ran `curl` under linux and got the desired result. 

*Thanks for your help*
