### ISSUE TITLE
Increase allowed Message Size

### ISSUE THREAD

**Issue by mrwhy-orig** [perwendel/spark#625]
HI there... 

is it anyhow possible to increase the allowed message size of the build in Jetty websocket server?

Thanks!

**Comment by AzureusNation** [comment]
Can you give an example of what you are trying to do to see if it is possible... or even a stacktrace would be great.

**Comment by mrwhy-orig** [comment]
Thanks for your reply but i got it in this moment.
The WebSocketPolicy has to be declared after all routes have been set: 
`WebSocketPolicy.newServerPolicy().setMaxTextMessageSize( YOURSIZE );`

**Comment by AzureusNation** [comment]
So what happens if you set the policy before the routes are added because if you add a route then the server gets started and this policy wont take effect?

**Comment by AzureusNation** [comment]
To be totally honest I don't think there is even away of doing this currently... There is no way to pass a policy to the server before or after ignition. @tipsy am I wrong?

**Comment by mrwhy-orig** [comment]
The behavior is a little bit strange... it already worked once. But at the moment i'm receiving the error again. I tried to set it before the Paths, in the Websockethandler, and behind but with no working result. Perhaps you are right and it is not possible to set it, but why have it then worked once?

**Comment by AzureusNation** [comment]
Who are you passing the new policy in to the server?

**Comment by mrwhy-orig** [comment]
I just call the newServerPolicy method of the WebSocketPolicy.class.

**Comment by AzureusNation** [comment]
Yeah that doesn't pass the policy into the Jetty server that is instantiated by Spark. Like I say I don't event think there is a way of doing this at the moment and with all of these types of issues now coming up about missing features I think that we are going to be in the mists of refactoring and rewriting some of the API (Just to clarify I have no input in the Spark project but I am getting deep in to the code). This is a future that needs to be added and I think there is another issue already about being able to customise the settings of Jetty.

@tipsy are you ok if I create a 3.x issue with tasks and add this to it and also go through the other issues that would be pushed back to version 3.x?

**Comment by mrwhy-orig** [comment]
Thanks for your help. Would be nice to have it in a future version. In the meantime i will use my workaround.

**Comment by GeorgeCGV** [comment]
If you wish to increase text and|or bin message size only you can do so using `org.eclipse.jetty.websocket.api.annotations.WebSocket` annotation parameters.
It looks this way:
`@WebSocket(maxTextMessageSize = 1048576, maxBinaryMessageSize = 1048576)
public class WebSocketEndpoint { ... }`

However, this won't allow you to set all possible Jetty websocket policies. 
Ideally, instead of `Spark.webSocketIdleTimeoutMillis(...);`, Spark must have something like `Spark.webSocketPolicy(...);` where you could provide either Jetty's  `WebSocketPolicy` or some Spark abstraction which is then will be used to populate related server settings. In this case (Jetty) it must be done within `WebSocketServletContextHandlerFactory`.

**Comment by tipsy** [comment]
This should hopefully also have been fixed by #813
