### ISSUE TITLE
Not able to deploy war properly

### ISSUE THREAD

**Issue by mddubey** [perwendel/spark#628]
Hello team,

I am trying to run my spark application as a `war` using default embedded jetty (tried with tomcat as well), but I'm facing some issues.

So here is the relevant part of my `build.gradle` file.

```
apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'war'
apply plugin: 'rpm'
apply plugin: 'idea'

repositories {
    mavenCentral()
    flatDir {
        dirs "${rootDir}/lib"
    }
}

dependencies {
   //list of dependencies
}

jar {
    baseName = 'mci-registry'
    version = '0.1-SNAPSHOT'
}

war {
    baseName = 'mci-registry'
    from sourceSets.main.resources
    manifest {
        attributes('Main-Class': mainClassName)
    }
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(
                'com.netflix.nebula:gradle-ospackage-plugin:2.2.+'
        )
    }
}
```

And here is the main class

```
public class Application {
    public static void main(String[] args) {
        get("/api/", (request, response) -> "Java 8");
    }
}
```

But when I say 

`gradle clean war && java -jar mci-registry.war`

It fails with error `Could not find or load main class org.sharedhealth.mci.web.launch.Application`.

If I see structure of war its like bellow

```
├── META-INF
│   └── MANIFEST.MF
├── WEB-INF
│   ├── classes
│   │   ├── log4j.xml
│   │   └── org
│   │       └── sharedhealth
│   │           └── mci
│   │               └── web
│   │                   └── launch
│   │                       └── Application.class
│   └── lib
│       ├── all jars
```

I think which is how a war-structure should be. References  [jetty](http://www.eclipse.org/jetty/documentation/9.4.x/configuring-deployment.html) & [tomcat](https://tomcat.apache.org/tomcat-7.0-doc/appdev/deployment.html). Though there should be an `web.xml` as well, but I saw spark docs and it says for jetty we don't need one.

I tried one more thing added bellow lines to `war` task of gradle

```
from "$buildDir/classes/main"
from {
    configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
```

This works by saying this `gradle clean war && java -jar mci-registry.war`.

But then I feel it's converted to a `jar` structure, not actually a war, because my `war` file contains all these files/folders

```
META-INF
WEB-INF
about.html
com
io
javax
jetty-dir.css
library.properties
log4j.xml
mci-registry.war
org
reflect.properties
rootdoc.txt
scala
spark
```

which I think is not correct. Let me know if I have missed something obvious or I misunderstood something.

Thank you

**Comment by victorwss** [comment]
Not sure if I understood correctly your problem.

A WAR file is something that is meant to be deployed at an application server. However, if you are using an embedded server, then it would simply make no sense to deploy it in an application server.

If you do that anyway, then there would be the actual application server A running the spark application which is running on top of another application server B. In this scenario requests received by A won't be delivered to B, making the Spark application useless since it sits on top of B's requests.

This could be fixed with some hacks to either make A deliver requests to B or make B get them independent of A. Either way, it won't make any sense to have it deployed in the A server instead of just having them running through a `public static void main(String[] args)` method on a JAR.

Maybe what you really want is to deploy a WAR in an application server without using the embedded server?
