### ISSUE TITLE
Set response body content is irrelevant

### ISSUE THREAD

**Issue by itaied246** [perwendel/spark#750]
I want to edit the body of the response using
`response.body()`
But spark routes return String, always.
So if I edit the body, the return override the response body!
Am I missing something?
What is the reason spark routes always return String?

**Comment by tipsy** [comment]
Normally you would just `return returnString;` instead of calling `response.body(String returnString)`;
It's done that way because it made more sense to us compared to editing the body after it's been set.
I think there's a hack where you can do `response.body("content");return "";`, where the body will not be overwritten by the return value, but I don't have the time to check it out right now.

**Comment by itaied246** [comment]
So could you say that `res.body()` is not useful?
Is there any reason to use that function?

**Comment by juliccr** [comment]
In fact, @itaied246 , a [spark.Route](https://github.com/perwendel/spark/blob/master/src/main/java/spark/Route.java) returns an Object. What are you trying to return? 

Maybe you could add your custom implementation of [spark.ResponseTransformer](https://github.com/perwendel/spark/blob/master/src/main/java/spark/ResponseTransformer.java) (i.e.: a json transformer) and use it as the third argument of the overloaded method of the  http-verb you are calling. For instance, if its a **post**, you should use the `public static void post(String path, Route route, ResponseTransformer transformer)` .

Hope it helps.

**Comment by tipsy** [comment]
> So could you say that res.body() is not useful?
> Is there any reason to use that function?
In my opinion it's useless/dangerous and shouldn't be used. The only potential use-case I can think of is if you're building/appending the response string in multiple locations, but that's already bad design IMO. I don't know why it's part of the API and I would like to see it gone in version 3.0.

**Comment by itaied246** [comment]
@juliccr I am trying to understand the purpose 
`res.body()` was written for.
Since `Route` return an object, I don't see a reason to modify the response body. 
I was looking for a way to modify the response body, and I find it easier to understand modifying the response body instead of returning an object.

**Comment by vitormcruz** [comment]
Why closing it? I got to this issue because the actual behavior is misleading. I actually find the body() function useful, I don't see why it is a bad design, and if the method is there spark should consider it if used instead of the return.  For now return res.body() at the end of the rout configuration as workaround..

**Comment by meawoppl** [comment]
After reading this issue, I am still not clear on the semantic of `.body()`

**Comment by gmohit5877** [comment]
what to do if want to return a response for xlsx file format
