### ISSUE TITLE
Best way to change the reason phrase

### ISSUE THREAD

**Issue by kiquetal** [perwendel/spark#772]
Inside Spark.Response, I could obtain the httpServletResponse, and did the following:
      HttpServletResponse h= res.raw();
    h.setStatus(404, "LOL ");
But IDE says it's depecrated.

There is another way?

**Comment by roqmarcelo** [comment]
This method was deprecated in the HttpServletResponse due to ambiguous meaning of the message parameter.

To set a status code, you should use `setStatus(int)`, to send an error with a description use `sendError(int, String)`.

That being said, your code should look like this:

`HttpServletTesponse h = res.raw();`
`h.setStatus(404, "LOL ");`

[Documentation](http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html)
