### ISSUE TITLE
calling halt(status, body) within exception() mapping doesn't preserve response content and status value

### ISSUE THREAD

**Issue by livingcreative** [perwendel/spark#805]
I have following setup after defining my routes

```java
exception(APIException.class, (ex, req, res) -> {
    String bodywitherrorinfo = /* format JSON response body with error info */;
    halt(ex.getStatus(), bodywitherrorinfo);
});
```

I'm sure, that `halt()` is called with correct `status` and `body` parameters, but I get empty response body on a client with 500 status. Is this behavior by design and I should use `res` parameter to set status and response contents "manually" or this is a bug?

**Comment by flexzuu** [comment]
I have the same issue.

**Comment by ernestomancebo** [comment]
As I could investigate, the ``exception`` mapping and ``halt`` both terminate the transaction throwing an exception and each is handled on it's respective block on ``spark.http.matching.MatcherFilter.doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain chain) throws IOException, ServletException
`` method.

At the moment that ``exception`` reaches the body wrapper in order to present a decent message as you try, a ``HaltException`` it's thrown and there's no handler at the ``exception`` for such exception at that scope, thus you don't get the desired message, instead a ``HaltException`` as in my case when I reproduced the scenario.

I could suggest to both of you to use halt when your business logic needs to stop the transaction and avoid using it under an exception scenario.

**Comment by tipsy** [comment]
Halt it not intended to be used in exception-mappers. I'll clarify that in the docs.
