### ISSUE TITLE
Add SameSite Cookie

### ISSUE THREAD

**Issue by Knight1** [perwendel/spark#835]
Hey,

would you please add the option to the response.cookie to set the SameSite Value?
This is only one single addition to the Set-Cookie header. 

RFC: https://tools.ietf.org/html/draft-west-first-party-cookies-06#section-4.1.1
http://caniuse.com/#search=SameSite

Thanks!

**Comment by Calico90** [comment]
For inspiration see: https://github.com/Calico90/CodeIgniterSecureCookies/blob/master/application/hooks/secureCookies.php

I did quite some research regarding the implementation of SameSite since it's not yet supported by PHP. In order to achieve this there is one important thing to consider. A different Set-Cookie header can be send multiple times. You might want to use some kind of output buffering in order to list the headers with headers_list() and to override them at the proper moment with the new version. Ping me if you have some questions.
